package it.dycomodel.admin.components.beans;


import java.io.Serializable;
import java.util.Date;
import java.util.Map;
import java.util.SortedMap;
import java.util.TreeMap;

import it.classhidra.core.tool.util.util_format;

public class DemoRawData implements Serializable{
	private static final long serialVersionUID = 1L;

	public static SortedMap<Long, Double> prepareDemoRawData(int year){
		TreeMap<Long, Double> result1 = new TreeMap<Long, Double>();
		try{
			TreeMap<Long, Double> result = new TreeMap<Long, Double>();
			for(int i=0;i<2;i++){
				result.put(util_format.stringToData((year+i)+"-1-4", "yyyy-MM-dd").getTime(), 224d);
				result.put(util_format.stringToData((year+i)+"-1-5", "yyyy-MM-dd").getTime(), 25d);
				result.put(util_format.stringToData((year+i)+"-1-6", "yyyy-MM-dd").getTime(), 72d);
				result.put(util_format.stringToData((year+i)+"-1-7", "yyyy-MM-dd").getTime(), 42d);
				result.put(util_format.stringToData((year+i)+"-1-9", "yyyy-MM-dd").getTime(), 171d);
				result.put(util_format.stringToData((year+i)+"-1-10", "yyyy-MM-dd").getTime(), 6d);
				result.put(util_format.stringToData((year+i)+"-1-12", "yyyy-MM-dd").getTime(), 70d);
				result.put(util_format.stringToData((year+i)+"-1-13", "yyyy-MM-dd").getTime(), 57d);
				result.put(util_format.stringToData((year+i)+"-1-14", "yyyy-MM-dd").getTime(), 5d);
				result.put(util_format.stringToData((year+i)+"-1-15", "yyyy-MM-dd").getTime(), 5d);
				result.put(util_format.stringToData((year+i)+"-1-16", "yyyy-MM-dd").getTime(), 91d);
				result.put(util_format.stringToData((year+i)+"-1-17", "yyyy-MM-dd").getTime(), 2d);
				result.put(util_format.stringToData((year+i)+"-1-19", "yyyy-MM-dd").getTime(), 88d);
				result.put(util_format.stringToData((year+i)+"-1-20", "yyyy-MM-dd").getTime(), 22d);
				result.put(util_format.stringToData((year+i)+"-1-23", "yyyy-MM-dd").getTime(), 15d);
				result.put(util_format.stringToData((year+i)+"-1-24", "yyyy-MM-dd").getTime(), 1d);
				result.put(util_format.stringToData((year+i)+"-1-25", "yyyy-MM-dd").getTime(), 1d);
				result.put(util_format.stringToData((year+i)+"-1-26", "yyyy-MM-dd").getTime(), 1d);
				result.put(util_format.stringToData((year+i)+"-1-27", "yyyy-MM-dd").getTime(), 49d);
				result.put(util_format.stringToData((year+i)+"-1-28", "yyyy-MM-dd").getTime(), 2d);
				result.put(util_format.stringToData((year+i)+"-1-29", "yyyy-MM-dd").getTime(), 1d);
				result.put(util_format.stringToData((year+i)+"-1-30", "yyyy-MM-dd").getTime(), 2d);
				result.put(util_format.stringToData((year+i)+"-1-31", "yyyy-MM-dd").getTime(), 6d);
				result.put(util_format.stringToData((year+i)+"-2-2", "yyyy-MM-dd").getTime(), 7d);
				result.put(util_format.stringToData((year+i)+"-2-3", "yyyy-MM-dd").getTime(), 4d);
				result.put(util_format.stringToData((year+i)+"-2-8", "yyyy-MM-dd").getTime(), 31d);
				result.put(util_format.stringToData((year+i)+"-2-9", "yyyy-MM-dd").getTime(), 2d);
				result.put(util_format.stringToData((year+i)+"-2-10", "yyyy-MM-dd").getTime(), 1d);
				result.put(util_format.stringToData((year+i)+"-2-11", "yyyy-MM-dd").getTime(), 1d);
				result.put(util_format.stringToData((year+i)+"-2-12", "yyyy-MM-dd").getTime(), 39d);
				result.put(util_format.stringToData((year+i)+"-2-13", "yyyy-MM-dd").getTime(), 9d);
				result.put(util_format.stringToData((year+i)+"-2-14", "yyyy-MM-dd").getTime(), 50d);
				result.put(util_format.stringToData((year+i)+"-2-15", "yyyy-MM-dd").getTime(), 2d);
				result.put(util_format.stringToData((year+i)+"-2-16", "yyyy-MM-dd").getTime(), 17d);
				result.put(util_format.stringToData((year+i)+"-2-17", "yyyy-MM-dd").getTime(), 40d);
				result.put(util_format.stringToData((year+i)+"-2-19", "yyyy-MM-dd").getTime(), 14d);
				result.put(util_format.stringToData((year+i)+"-2-20", "yyyy-MM-dd").getTime(), 6d);
				result.put(util_format.stringToData((year+i)+"-2-21", "yyyy-MM-dd").getTime(), 1d);
				result.put(util_format.stringToData((year+i)+"-2-22", "yyyy-MM-dd").getTime(), 15d);
				result.put(util_format.stringToData((year+i)+"-2-23", "yyyy-MM-dd").getTime(), 104d);
				result.put(util_format.stringToData((year+i)+"-2-24", "yyyy-MM-dd").getTime(), 80d);
				result.put(util_format.stringToData((year+i)+"-2-25", "yyyy-MM-dd").getTime(), 2d);
				result.put(util_format.stringToData((year+i)+"-2-26", "yyyy-MM-dd").getTime(), 17d);
				result.put(util_format.stringToData((year+i)+"-2-27", "yyyy-MM-dd").getTime(), 11d);
				result.put(util_format.stringToData((year+i)+"-2-28", "yyyy-MM-dd").getTime(), 18d);
				result.put(util_format.stringToData((year+i)+"-2-29", "yyyy-MM-dd").getTime(), 29d);
				result.put(util_format.stringToData((year+i)+"-3-1", "yyyy-MM-dd").getTime(), 50d);
				result.put(util_format.stringToData((year+i)+"-3-2", "yyyy-MM-dd").getTime(), 4d);
				result.put(util_format.stringToData((year+i)+"-3-3", "yyyy-MM-dd").getTime(), 60d);
				result.put(util_format.stringToData((year+i)+"-3-4", "yyyy-MM-dd").getTime(), 71d);
				result.put(util_format.stringToData((year+i)+"-3-5", "yyyy-MM-dd").getTime(), 20d);
				result.put(util_format.stringToData((year+i)+"-3-6", "yyyy-MM-dd").getTime(), 15d);
				result.put(util_format.stringToData((year+i)+"-3-7", "yyyy-MM-dd").getTime(), 24d);
				result.put(util_format.stringToData((year+i)+"-3-8", "yyyy-MM-dd").getTime(), 24d);
				result.put(util_format.stringToData((year+i)+"-3-10", "yyyy-MM-dd").getTime(), 35d);
				result.put(util_format.stringToData((year+i)+"-3-11", "yyyy-MM-dd").getTime(), 24d);
				result.put(util_format.stringToData((year+i)+"-3-13", "yyyy-MM-dd").getTime(), 22d);
				result.put(util_format.stringToData((year+i)+"-3-15", "yyyy-MM-dd").getTime(), 21d);
				result.put(util_format.stringToData((year+i)+"-3-16", "yyyy-MM-dd").getTime(), 221d);
				result.put(util_format.stringToData((year+i)+"-3-17", "yyyy-MM-dd").getTime(), 127d);
				result.put(util_format.stringToData((year+i)+"-3-20", "yyyy-MM-dd").getTime(), 13d);
				result.put(util_format.stringToData((year+i)+"-3-21", "yyyy-MM-dd").getTime(), 10d);
				result.put(util_format.stringToData((year+i)+"-3-22", "yyyy-MM-dd").getTime(), 19d);
				result.put(util_format.stringToData((year+i)+"-3-23", "yyyy-MM-dd").getTime(), 18d);
				result.put(util_format.stringToData((year+i)+"-3-24", "yyyy-MM-dd").getTime(), 18d);
				result.put(util_format.stringToData((year+i)+"-3-27", "yyyy-MM-dd").getTime(), 11d);
				result.put(util_format.stringToData((year+i)+"-3-29", "yyyy-MM-dd").getTime(), 19d);
				result.put(util_format.stringToData((year+i)+"-3-30", "yyyy-MM-dd").getTime(), 11d);
				result.put(util_format.stringToData((year+i)+"-3-31", "yyyy-MM-dd").getTime(), 16d);
				result.put(util_format.stringToData((year+i)+"-4-3", "yyyy-MM-dd").getTime(), 12d);
				result.put(util_format.stringToData((year+i)+"-4-4", "yyyy-MM-dd").getTime(), 112d);
				result.put(util_format.stringToData((year+i)+"-4-5", "yyyy-MM-dd").getTime(), 113d);
				result.put(util_format.stringToData((year+i)+"-4-8", "yyyy-MM-dd").getTime(), 15d);
				result.put(util_format.stringToData((year+i)+"-4-11", "yyyy-MM-dd").getTime(), 113d);
				result.put(util_format.stringToData((year+i)+"-4-12", "yyyy-MM-dd").getTime(), 111d);
				result.put(util_format.stringToData((year+i)+"-4-15", "yyyy-MM-dd").getTime(), 13d);
				result.put(util_format.stringToData((year+i)+"-4-16", "yyyy-MM-dd").getTime(), 144d);
				result.put(util_format.stringToData((year+i)+"-4-18", "yyyy-MM-dd").getTime(), 11d);
				result.put(util_format.stringToData((year+i)+"-4-21", "yyyy-MM-dd").getTime(), 11d);
				result.put(util_format.stringToData((year+i)+"-4-22", "yyyy-MM-dd").getTime(), 11d);
				result.put(util_format.stringToData((year+i)+"-4-23", "yyyy-MM-dd").getTime(), 16d);
				result.put(util_format.stringToData((year+i)+"-4-28", "yyyy-MM-dd").getTime(), 17d);
				result.put(util_format.stringToData((year+i)+"-4-29", "yyyy-MM-dd").getTime(), 13d);
				result.put(util_format.stringToData((year+i)+"-5-4", "yyyy-MM-dd").getTime(), 1d);
				result.put(util_format.stringToData((year+i)+"-5-5", "yyyy-MM-dd").getTime(), 2d);
				result.put(util_format.stringToData((year+i)+"-5-6", "yyyy-MM-dd").getTime(), 10d);
				result.put(util_format.stringToData((year+i)+"-5-11", "yyyy-MM-dd").getTime(), 2d);
				result.put(util_format.stringToData((year+i)+"-5-12", "yyyy-MM-dd").getTime(), 4d);
				result.put(util_format.stringToData((year+i)+"-5-13", "yyyy-MM-dd").getTime(), 9d);
				result.put(util_format.stringToData((year+i)+"-5-17", "yyyy-MM-dd").getTime(), 21d);
				result.put(util_format.stringToData((year+i)+"-5-18", "yyyy-MM-dd").getTime(), 200d);
				result.put(util_format.stringToData((year+i)+"-5-19", "yyyy-MM-dd").getTime(), 22d);
				result.put(util_format.stringToData((year+i)+"-5-21", "yyyy-MM-dd").getTime(), 31d);
				result.put(util_format.stringToData((year+i)+"-5-22", "yyyy-MM-dd").getTime(), 41d);
				result.put(util_format.stringToData((year+i)+"-5-23", "yyyy-MM-dd").getTime(), 37d);
				result.put(util_format.stringToData((year+i)+"-5-24", "yyyy-MM-dd").getTime(), 3d);
				result.put(util_format.stringToData((year+i)+"-5-25", "yyyy-MM-dd").getTime(), 2d);
				result.put(util_format.stringToData((year+i)+"-5-27", "yyyy-MM-dd").getTime(), 5d);
				result.put(util_format.stringToData((year+i)+"-5-30", "yyyy-MM-dd").getTime(), 2d);
				result.put(util_format.stringToData((year+i)+"-6-3", "yyyy-MM-dd").getTime(), 2d);
				result.put(util_format.stringToData((year+i)+"-6-8", "yyyy-MM-dd").getTime(), 8d);
				result.put(util_format.stringToData((year+i)+"-6-10", "yyyy-MM-dd").getTime(), 67d);
				result.put(util_format.stringToData((year+i)+"-6-13", "yyyy-MM-dd").getTime(), 1d);
				result.put(util_format.stringToData((year+i)+"-6-14", "yyyy-MM-dd").getTime(), 5d);
				result.put(util_format.stringToData((year+i)+"-6-15", "yyyy-MM-dd").getTime(), 13d);
				result.put(util_format.stringToData((year+i)+"-6-16", "yyyy-MM-dd").getTime(), 1d);
				result.put(util_format.stringToData((year+i)+"-6-17", "yyyy-MM-dd").getTime(), 1d);
				result.put(util_format.stringToData((year+i)+"-6-21", "yyyy-MM-dd").getTime(), 12d);
				result.put(util_format.stringToData((year+i)+"-6-22", "yyyy-MM-dd").getTime(), 36d);
				result.put(util_format.stringToData((year+i)+"-6-23", "yyyy-MM-dd").getTime(), 9d);
				result.put(util_format.stringToData((year+i)+"-6-24", "yyyy-MM-dd").getTime(), 5d);
				result.put(util_format.stringToData((year+i)+"-6-25", "yyyy-MM-dd").getTime(), 2d);
				result.put(util_format.stringToData((year+i)+"-6-27", "yyyy-MM-dd").getTime(), 11d);
				result.put(util_format.stringToData((year+i)+"-6-28", "yyyy-MM-dd").getTime(), 211d);
				result.put(util_format.stringToData((year+i)+"-6-29", "yyyy-MM-dd").getTime(), 3d);
				result.put(util_format.stringToData((year+i)+"-6-30", "yyyy-MM-dd").getTime(), 30d);
				result.put(util_format.stringToData((year+i)+"-7-1", "yyyy-MM-dd").getTime(), 5d);
				result.put(util_format.stringToData((year+i)+"-7-3", "yyyy-MM-dd").getTime(), 272d);
				result.put(util_format.stringToData((year+i)+"-7-4", "yyyy-MM-dd").getTime(), 1d);
				result.put(util_format.stringToData((year+i)+"-7-5", "yyyy-MM-dd").getTime(), 49d);
				result.put(util_format.stringToData((year+i)+"-7-6", "yyyy-MM-dd").getTime(), 9d);
				result.put(util_format.stringToData((year+i)+"-7-11", "yyyy-MM-dd").getTime(), 3d);
				result.put(util_format.stringToData((year+i)+"-7-12", "yyyy-MM-dd").getTime(), 7d);
				result.put(util_format.stringToData((year+i)+"-7-13", "yyyy-MM-dd").getTime(), 19d);
				result.put(util_format.stringToData((year+i)+"-7-15", "yyyy-MM-dd").getTime(), 22d);
				result.put(util_format.stringToData((year+i)+"-7-16", "yyyy-MM-dd").getTime(), 2d);
				result.put(util_format.stringToData((year+i)+"-7-17", "yyyy-MM-dd").getTime(), 267d);
				result.put(util_format.stringToData((year+i)+"-7-18", "yyyy-MM-dd").getTime(), 55d);
				result.put(util_format.stringToData((year+i)+"-7-20", "yyyy-MM-dd").getTime(), 10d);
				result.put(util_format.stringToData((year+i)+"-7-21", "yyyy-MM-dd").getTime(), 84d);
				result.put(util_format.stringToData((year+i)+"-7-22", "yyyy-MM-dd").getTime(), 39d);
				result.put(util_format.stringToData((year+i)+"-7-23", "yyyy-MM-dd").getTime(), 23d);
				result.put(util_format.stringToData((year+i)+"-7-24", "yyyy-MM-dd").getTime(), 11d);
				result.put(util_format.stringToData((year+i)+"-7-25", "yyyy-MM-dd").getTime(), 8d);
				result.put(util_format.stringToData((year+i)+"-7-26", "yyyy-MM-dd").getTime(), 21d);
				result.put(util_format.stringToData((year+i)+"-7-28", "yyyy-MM-dd").getTime(), 8d);
				result.put(util_format.stringToData((year+i)+"-7-29", "yyyy-MM-dd").getTime(), 293d);
				result.put(util_format.stringToData((year+i)+"-7-31", "yyyy-MM-dd").getTime(), 88d);
				result.put(util_format.stringToData((year+i)+"-8-1", "yyyy-MM-dd").getTime(), 24d);
				result.put(util_format.stringToData((year+i)+"-8-3", "yyyy-MM-dd").getTime(), 69d);
				result.put(util_format.stringToData((year+i)+"-8-4", "yyyy-MM-dd").getTime(), 54d);
				result.put(util_format.stringToData((year+i)+"-8-5", "yyyy-MM-dd").getTime(), 1d);
				result.put(util_format.stringToData((year+i)+"-8-7", "yyyy-MM-dd").getTime(), 111d);
				result.put(util_format.stringToData((year+i)+"-8-8", "yyyy-MM-dd").getTime(), 71d);
				result.put(util_format.stringToData((year+i)+"-8-9", "yyyy-MM-dd").getTime(), 9d);
				result.put(util_format.stringToData((year+i)+"-8-10", "yyyy-MM-dd").getTime(), 108d);
				result.put(util_format.stringToData((year+i)+"-8-25", "yyyy-MM-dd").getTime(), 12d);
				result.put(util_format.stringToData((year+i)+"-8-28", "yyyy-MM-dd").getTime(), 9d);
				result.put(util_format.stringToData((year+i)+"-8-29", "yyyy-MM-dd").getTime(), 97d);
				result.put(util_format.stringToData((year+i)+"-8-31", "yyyy-MM-dd").getTime(), 3d);
				result.put(util_format.stringToData((year+i)+"-9-1", "yyyy-MM-dd").getTime(), 4d);
				result.put(util_format.stringToData((year+i)+"-9-2", "yyyy-MM-dd").getTime(), 14d);
				result.put(util_format.stringToData((year+i)+"-9-3", "yyyy-MM-dd").getTime(), 26d);
				result.put(util_format.stringToData((year+i)+"-9-5", "yyyy-MM-dd").getTime(), 2d);
				result.put(util_format.stringToData((year+i)+"-9-7", "yyyy-MM-dd").getTime(), 9d);
				result.put(util_format.stringToData((year+i)+"-9-8", "yyyy-MM-dd").getTime(), 1d);
				result.put(util_format.stringToData((year+i)+"-9-9", "yyyy-MM-dd").getTime(), 52d);
				result.put(util_format.stringToData((year+i)+"-9-10", "yyyy-MM-dd").getTime(), 18d);
				result.put(util_format.stringToData((year+i)+"-9-11", "yyyy-MM-dd").getTime(), 11d);
				result.put(util_format.stringToData((year+i)+"-9-14", "yyyy-MM-dd").getTime(), 5d);
				result.put(util_format.stringToData((year+i)+"-9-15", "yyyy-MM-dd").getTime(), 4d);
				result.put(util_format.stringToData((year+i)+"-9-16", "yyyy-MM-dd").getTime(), 112d);
				result.put(util_format.stringToData((year+i)+"-9-18", "yyyy-MM-dd").getTime(), 7d);
				result.put(util_format.stringToData((year+i)+"-9-20", "yyyy-MM-dd").getTime(), 5d);
				result.put(util_format.stringToData((year+i)+"-9-22", "yyyy-MM-dd").getTime(), 4d);
				result.put(util_format.stringToData((year+i)+"-9-23", "yyyy-MM-dd").getTime(), 5d);
				result.put(util_format.stringToData((year+i)+"-9-27", "yyyy-MM-dd").getTime(), 4d);
				result.put(util_format.stringToData((year+i)+"-10-4", "yyyy-MM-dd").getTime(), 4d);
				result.put(util_format.stringToData((year+i)+"-10-5", "yyyy-MM-dd").getTime(), 8d);
				result.put(util_format.stringToData((year+i)+"-10-6", "yyyy-MM-dd").getTime(), 3d);
				result.put(util_format.stringToData((year+i)+"-10-7", "yyyy-MM-dd").getTime(), 1d);
				result.put(util_format.stringToData((year+i)+"-10-9", "yyyy-MM-dd").getTime(), 3d);
				result.put(util_format.stringToData((year+i)+"-10-12", "yyyy-MM-dd").getTime(), 2d);
				result.put(util_format.stringToData((year+i)+"-10-14", "yyyy-MM-dd").getTime(), 25d);
				result.put(util_format.stringToData((year+i)+"-10-17", "yyyy-MM-dd").getTime(), 18d);
				result.put(util_format.stringToData((year+i)+"-10-19", "yyyy-MM-dd").getTime(), 8d);
				result.put(util_format.stringToData((year+i)+"-10-23", "yyyy-MM-dd").getTime(), 4d);
				result.put(util_format.stringToData((year+i)+"-10-24", "yyyy-MM-dd").getTime(), 14d);
				result.put(util_format.stringToData((year+i)+"-10-27", "yyyy-MM-dd").getTime(), 2d);
				result.put(util_format.stringToData((year+i)+"-10-28", "yyyy-MM-dd").getTime(), 2d);
				result.put(util_format.stringToData((year+i)+"-10-30", "yyyy-MM-dd").getTime(), 27d);
				result.put(util_format.stringToData((year+i)+"-11-3", "yyyy-MM-dd").getTime(), 1d);
				result.put(util_format.stringToData((year+i)+"-11-4", "yyyy-MM-dd").getTime(), 14d);
				result.put(util_format.stringToData((year+i)+"-11-5", "yyyy-MM-dd").getTime(), 7d);
				result.put(util_format.stringToData((year+i)+"-11-6", "yyyy-MM-dd").getTime(), 10d);
				result.put(util_format.stringToData((year+i)+"-11-7", "yyyy-MM-dd").getTime(), 4d);
				result.put(util_format.stringToData((year+i)+"-11-8", "yyyy-MM-dd").getTime(), 2d);
				result.put(util_format.stringToData((year+i)+"-11-9", "yyyy-MM-dd").getTime(), 9d);
				result.put(util_format.stringToData((year+i)+"-11-10", "yyyy-MM-dd").getTime(), 2d);
				result.put(util_format.stringToData((year+i)+"-11-15", "yyyy-MM-dd").getTime(), 29d);
				result.put(util_format.stringToData((year+i)+"-11-16", "yyyy-MM-dd").getTime(), 5d);
				result.put(util_format.stringToData((year+i)+"-11-17", "yyyy-MM-dd").getTime(), 3d);
				result.put(util_format.stringToData((year+i)+"-11-18", "yyyy-MM-dd").getTime(), 2d);
				result.put(util_format.stringToData((year+i)+"-11-21", "yyyy-MM-dd").getTime(), 11d);
				result.put(util_format.stringToData((year+i)+"-11-22", "yyyy-MM-dd").getTime(), 11d);
				result.put(util_format.stringToData((year+i)+"-11-25", "yyyy-MM-dd").getTime(), 11d);
				result.put(util_format.stringToData((year+i)+"-11-26", "yyyy-MM-dd").getTime(), 3d);
				result.put(util_format.stringToData((year+i)+"-12-1", "yyyy-MM-dd").getTime(), 7d);
				result.put(util_format.stringToData((year+i)+"-12-2", "yyyy-MM-dd").getTime(), 71d);
				result.put(util_format.stringToData((year+i)+"-12-4", "yyyy-MM-dd").getTime(), 5d);
				result.put(util_format.stringToData((year+i)+"-12-7", "yyyy-MM-dd").getTime(), 7d);
				result.put(util_format.stringToData((year+i)+"-12-13", "yyyy-MM-dd").getTime(), 34d);
				result.put(util_format.stringToData((year+i)+"-12-14", "yyyy-MM-dd").getTime(), 44d);
				result.put(util_format.stringToData((year+i)+"-12-17", "yyyy-MM-dd").getTime(), 24d);
				result.put(util_format.stringToData((year+i)+"-12-18", "yyyy-MM-dd").getTime(), 1d);
				result.put(util_format.stringToData((year+i)+"-12-19", "yyyy-MM-dd").getTime(), 60d);
				result.put(util_format.stringToData((year+i)+"-12-20", "yyyy-MM-dd").getTime(), 165d);
				result.put(util_format.stringToData((year+i)+"-12-22", "yyyy-MM-dd").getTime(), 67d);
				result.put(util_format.stringToData((year+i)+"-12-23", "yyyy-MM-dd").getTime(), 18d);
				result.put(util_format.stringToData((year+i)+"-12-28", "yyyy-MM-dd").getTime(), 44d);
				result.put(util_format.stringToData((year+i)+"-12-29", "yyyy-MM-dd").getTime(), 29d);
			}
			Date current = new Date();
			for(Map.Entry<Long, Double> entry: result.entrySet()){
				if(entry.getKey().longValue()<current.getTime())
					result1.put(entry.getKey(),entry.getValue());
			}
		}catch(Exception e){
			
		}
		return result1;
	}
	
}
